# Generated by Django 4.1 on 2022-08-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmoArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument', models.TextField()),
                ('arg_strength', models.FloatField()),
                ('stance', models.IntegerField()),
                ('topic', models.TextField()),
                ('label', models.PositiveIntegerField()),
            ],
        ),
    ]
