# Generated by Django 4.1 on 2022-08-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmoArguments',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('argument', models.TextField()),
                ('arg_strength', models.FloatField()),
                ('topic', models.TextField()),
                ('stance', models.PositiveIntegerField()),
                ('label', models.PositiveIntegerField()),
            ],
        ),
    ]
